<nav class="navbar navbar-expand-lg navbar-white bg-white pb-3 shadow">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="../">Go to site <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <li class="nav-item dropdown list-unstyled ">
              <button class="btn btn-dark my-2 my-sm-0 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ><?= $_SESSION['user'] ?></button>            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <button class="dropdown-item text-white bg-danger" href="#">Logout</button>
            </div>
          </li>
          
        </div>
      </nav>