        <main role="main" class="main-content col-md-9  col-lg-12 px-4"><div style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center  pb-2 mb-3 border-bottom" >
            <h1 class="h2">Products</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                This week
              </button>
            </div>
            
        </div>
        <div class="col">
            <!-- Top nav -->
              <!-- center -->
          <div class="row">
                    <div class="table-responsive table--no-card m-b-40 col-10 pl-0">
                      <table class="table table-borderless table-striped table-earning">
                          <!-- Titles -->
                        <thead>
                          <tr>
                            <th>ID</th>
                            <th>Image</th>
                            <th class="max-width">Title</th>
                            <th class="sortable">description</th>
                            <th>Price</th>
                            <th>Category</th>
                            <th>Actions</th>
                          </tr>
                        </thead>
                        <!-- Content -->
                        <tbody>
                            <?php
                                $rows=$product->getProducts();
                                 foreach ($rows as $row) {?>
                            <tr>
                              <td class="text-nowrap align-middle"><?=$row['ID']; ?></td>
                              <td class="align-middle text-center">
                              <div class="bg-light d-inline-flex justify-content-center align-items-center align-top" style="width: 35px; height: 35px; border-radius: 3px;"><button data-toggle="modal" data-target="#imageP<?=$row['ID'];?>"><i class="fa fa-fw fa-photo" style="opacity: 0.8;"></i></button></div>
                              </td>
                              <td class="text-nowrap align-middle"><span><?=$row['name']; ?></span></td>
                              <td class="text-center align-middle " style="  display: block;
  width: 200px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;"><small><?=$row['description']; ?></small></td>
                              <td class="text-center align-middle"><?=$row['price']; ?></td>
                              <td class="text-center align-middle"><?=categoryName($row['category'])?></td>
                                  <!-- <i class="fa fa-fw text-secondary cursor-pointer fa-toggle-on"></i> -->
                              <td class="text-center align-middle">
                                <div class="table-data-feature">
                                    <button class="item" type="button" data-toggle="modal" data-target="#user-edit-modal<?=$row['ID'];?>"><i class="zmdi zmdi-edit"></i></button>
                                    <button class="item" type="button" data-toggle="modal" data-target="#user-delete-modal<?=$row['ID'];?>"><i class="zmdi zmdi-delete"></i></button>
                                  </div>
                                </td>
                              </tr>
                              <?php include 'imageP.php';
                              include 'Pdelete.phtml';
                              include 'Pupdate.old.php';
 } ?>
                        </tbody>
                      </table>
                    </div>
            <!-- Right settings -->
            <div class="col-2">
                  <div class="text-center ">
                    <button class="btn btn-success btn-block" type="button" style="border-radius:10px" data-toggle="modal" data-target="#user-form-modal">New Product</button>
                  </div>
                  <hr class="my-3">
                  <div class="alert alert-danger" style='display:<?=isset($msg)?"block":"none"?>!important'>

                      <?=isset($msg)?$msg:''?>
                      </div>
                </div>
              </div>
            </div>
          </div>
      
          <!-- User Form Modal -->
          <?php
            include 'Pcreate.phtml';
          ?>
        </div>
        </main>
      </div>     
      