        <main role="main" class="col-md-9 ml-sm-auto col-lg-12 px-4"><div style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom" style="padding-top:80px!important">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
                This week
              </button>
            </div>
            
        </div>
        <div class="col">
              <!-- center -->
              <div class="row">
                <div class="table-responsive table--no-card m-b-40 col-10 pl-0">
                      <table class="table table-borderless table-striped table-earning">
                                          <thead>
                                                <tr>
                                                <th>ID</th>
                                                <th >Title</th>
                                                <th class="max-width">description</th>
                                                <th>Actions</th>
                                                </tr>
                                          </thead>
                                          <tbody>
                                          <?php
                                  $rows=getCategories();
                                  foreach($rows as $row){?>
                              <tr>
                                
                                <td class="text-nowrap align-middle"><?php echo $row['ID'];?></td>
                                <td class="text-nowrap align-middle"><span><?=$row['name'];?></span></td>
                                <td class="text-center align-middle"><?=$row['description'];?></td>
                                <td class="text-center align-middle">
                                  <div class="table-data-feature">
                                      <button class="item"id=<?=$row['ID'];?> type="button" data-toggle="modal" data-target="#user-update-modal<?php echo $row['ID']?>"><i class="zmdi zmdi-edit"></i></button>
                                      <button class="item" type="button" data-toggle="modal" data-target="#user-delete-modal<?php echo $row['ID']?>"><i class="zmdi zmdi-delete"></i></button>
                                  </div>

                                </td>
                              </tr>
                              <?php
                                  include 'Cupdate.phtml';
                                  include 'Cdelete.phtml';
                              }?>
                                          </tbody>
                      </table>
                </div>
                <!-- Right settings -->
            <div class="col-2 " >
                   <div class="text-center ">
                    <button class="btn btn-success btn-block" style="border-radius:10px" type="button" data-toggle="modal" data-target="#user-form-modal">New Category</button>
              </div>
            </div>
              </div>

            
      
          <!-- User Form Modal -->
          <?php include 'Ccreate.phtml'; ?>
        </div>
        </main>
      </div>
