<div class="modal fade" role="dialog" tabindex="-1" id="user-form-modal<?=$row['ID'];?>">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Client details</h5>
                  <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="py-1">
                      <div class="row">
                        <div class="col">
                          <div class="row">
                            <div class="col">
                                <label>Name:</label>
                                <h6><?=$row['name']?></h6>
                            </div>
                            <div class="col">
                                <label>Telephone:</label>
                                <h6><?=$row['phone']?></h6>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                        <div class="col">
                            <label>Adresse:</label>
                            <h6><?=$row['adresse']?></h6>
                        </div>
                        <div class="col">
                            <label>Adresse email:</label>
                            <h6><?=$row['email']?></h6>
                        </div>
                        </div>


                          <div class="row">
                              <div class="col">
                                <div class="form-group float-right">
                                  <button type="reset" data-dismiss="modal" class="btn btn-danger float" >Close</button>
                                </div>
                              </div>
                            </div>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>