
        <main role="main" class="main-content col-md-9 ml-sm-auto col-lg-12 px-4"><div style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1; " class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center   mb-2 border-bottom">
            <h1 class="h2">Customers</h1>

            
        </div>
        <div class="col">
            <!-- Top nav -->
          <!-- <div class="e-tabs  px-3">
            <ul class="nav nav-tabs">
              <li class="nav-item"><a class="nav-link active" href="#">Products</a></li>
            </ul>
          </div> -->
              <!-- center -->
              <div class="table-responsive table--no-card m-b-40 col-12 pl-0">
                      <table class="table table-borderless table-striped table-earning">

                          <!-- Titles -->
                        <thead>
                          <tr>
                           
                            <th>ID</th>
                            <th>Nom de client</th>
                            <th>Telephone</th>
                            <th>Adresse</th>
                            <th>actions</th>
                          </tr>
                        </thead>
                        <!-- Content -->
                        <tbody>
                            <?php foreach ($rows as $row): ?>
                          <tr>
                             
                              <td class="text-nowrap align-middle"><?=$row['ID']?></td>
                              <td class="text-nowrap align-middle"><span> <?=$row['name']?></span></td>
                              <td class="text-center align-middle"> <?=$row['phone']?></td> 
                              <td class="text-center align-middle"> <?=$row['adresse']?></td>
                                  <!-- <i class="fa fa-fw text-secondary cursor-pointer fa-toggle-on"></i> -->
                              <td class="text-center align-middle">
                                <div class="table-data-feature">
                                    <button class="item" type="button" data-toggle="modal" data-target="#user-form-modal<?=$row['ID'];?>"><i class="zmdi zmdi-more"></i></button>
                                    <?php include 'details.php'?>
                                </div>
                              </td>                                
                            </tr>
                                <?php endforeach; ?>
                        </tbody>
                      </table>
                </div>
                
          </div>
      
          <!-- User Form Modal -->
                
        </div>
        </main>
      </div>