

  <!-- food section -->
  <div class="alert text-center alert-success <?=isset($done)&&$done==1?"":"d-none"?>" role="alert">
  <h2>Item added to card</h2>
</div>
  <section class="mt-5 food_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Menu
        </h2>
      </div>

      <ul class="filters_menu">
        <li class="active" data-filter="*">All</li>
        <?php foreach($rows as $row){?>
              <li data-filter=".<?= $row["name"];?>"><?= $row["name"];?></li>
        <?php 
      }
      ?>
      </ul>

      <div class="filters-content">
        <div class="row grid">
        <?php foreach($rows1 as $row){
          productShowMenu($row['category'],$row['image'],$row['name'],$row['description'],$row['price'],$row['ID']);
}?>
        </div>
      </div>
      <div class="btn-box">
        <a href="panier.php">
          View Cart
        </a>
      </div>
    </div>
  </section>


  <!-- end food section -->
