<div class="modal fade" role="dialog" tabindex="-1" id="user-form-modal">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Create User</h5>
                  <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="py-1">
                    <form class="form" method="post" action="Ccreate.php" novalidate="">
                      <div class="row">
                        <div class="col">
                          <div class="row">
                            <div class="col">
                              <div class="form-group">
                                <label>Name</label>
                                <input class="form-control" type="text" name="name" placeholder="Pizza 4fromage" >
                              </div>
                            </div>
                            <div class="col">
                              <div class="form-group">
                                <label>Description</label>
                                <input class="form-control" type="text" name="description" placeholder="Thon,Tomate,Fromage,Piment" >
                              </div>
                            </div>
                          </div>

                          <div class="row">
                              <div class="col">
                                <div class="form-group float-right">
                                  <button type="reset" data-dismiss="modal" class="btn btn-danger float" >Cancel</button>
                                  <button type="submit" class="btn btn-primary float" >Ajouter</button>
                                </div>
                              </div>
                            </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>