

    <div class="page-wrapper">
     
     <!-- MAIN CONTENT-->
     <div class="main-content">
         <div class="section__content section__content--p30">
             <div class="container-fluid">
                 <div class="row">
                     <div class="col-md-12">
                         <div class="overview-wrap">
                             <h2 class="title-1">overview</h2>
                         </div>
                     </div>
                 </div>
                 <div class="row m-t-25">
                     <div class="col-sm-6 col-lg-3">
                         <div class="overview-item overview-item--c1">
                             <div class="overview__inner">
                                 <div class="overview-box clearfix">
                                     <div class="icon">
                                         <i class="zmdi zmdi-account-o"></i>
                                     </div>
                                     <div class="text">
                                         <h2><?= $clientCount ?></h2>
                                         <span>members online</span>
                                     </div>
                                 </div>
                                 <div class="overview-chart">
                                     <canvas id="widgetChart1"></canvas>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-6 col-lg-3">
                         <div class="overview-item overview-item--c2">
                             <div class="overview__inner">
                                 <div class="overview-box clearfix">
                                     <div class="icon">
                                         <i class="zmdi zmdi-shopping-cart"></i>
                                     </div>
                                     <div class="text">
                                         <h2><?= $orderCount?></h2>
                                         <span>items solid</span>
                                     </div>
                                 </div>
                                 <div class="overview-chart">
                                     <canvas id="widgetChart2"></canvas>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-6 col-lg-3">
                         <div class="overview-item overview-item--c3">
                             <div class="overview__inner">
                                 <div class="overview-box clearfix">
                                     <div class="icon">
                                         <i class="zmdi zmdi-calendar-note"></i>
                                     </div>
                                     <div class="text">
                                         <h2>1,086</h2>
                                         <span>this week</span>
                                     </div>
                                 </div>
                                 <div class="overview-chart">
                                     <canvas id="widgetChart3"></canvas>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-6 col-lg-3">
                         <div class="overview-item overview-item--c4">
                             <div class="overview__inner">
                                 <div class="overview-box clearfix">
                                     <div class="icon">
                                         <i class="zmdi zmdi-money"></i>
                                     </div>
                                     <div class="text">
                                         <h2><?=$totalEarnings?>Tnd</h2>
                                         <span>total earnings</span>
                                     </div>
                                 </div>
                                 <div class="overview-chart">
                                     <canvas id="widgetChart4"></canvas>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <!-- <div class="row">
                     <div class="col-lg-6">
                         <div class="au-card recent-report">
                             <div class="au-card-inner">
                                 <h3 class="title-2">recent reports</h3>
                                 <div class="chart-info">
                                     <div class="chart-info__left">
                                         <div class="chart-note">
                                             <span class="dot dot--blue"></span>
                                             <span>products</span>
                                         </div>
                                         <div class="chart-note mr-0">
                                             <span class="dot dot--green"></span>
                                             <span>services</span>
                                         </div>
                                     </div>
                                     <div class="chart-info__right">
                                         <div class="chart-statis">
                                             <span class="index incre">
                                                 <i class="zmdi zmdi-long-arrow-up"></i>25%</span>
                                             <span class="label">products</span>
                                         </div>
                                         <div class="chart-statis mr-0">
                                             <span class="index decre">
                                                 <i class="zmdi zmdi-long-arrow-down"></i>10%</span>
                                             <span class="label">services</span>
                                         </div>
                                     </div>
                                 </div>
                                 <div class="recent-report__chart">
                                     <canvas id="recent-rep-chart"></canvas>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div class="col-lg-6">
                         <div class="au-card chart-percent-card">
                             <div class="au-card-inner">
                                 <h3 class="title-2 tm-b-5">char by %</h3>
                                 <div class="row no-gutters">
                                     <div class="col-xl-6">
                                         <div class="chart-note-wrap">
                                             <div class="chart-note mr-0 d-block">
                                                 <span class="dot dot--blue"></span>
                                                 <span>products</span>
                                             </div>
                                             <div class="chart-note mr-0 d-block">
                                                 <span class="dot dot--red"></span>
                                                 <span>services</span>
                                             </div>
                                         </div>
                                     </div>
                                     <div class="col-xl-6">
                                         <div class="percent-chart">
                                             <canvas id="percent-chart"></canvas>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div> -->
                 <div class="row">
                     <div class="col-lg-9">
                         <h2 class="title-1 m-b-25">Earnings By Product</h2>
                         <div class="table-responsive table--no-card m-b-40">
                             <table class="table table-borderless table-striped table-earning">
                                 <thead>
                                     <tr>
                                     <th>ID</th>
                                     <th class="max-width">Title</th>
                                     <th class="sortable">description</th>
                                     <th>Total earning</th>
                                     <th>Category</th>
                                     </tr>
                                 </thead>
                                 <tbody>
                                 <?php
                          foreach ($productEarnings as $r) {
                              $row=getProductId($r['p'])
                              ?>
                     <tr>
                       <td class="text-nowrap align-middle"><?=$row['ID']; ?></td>
                       <td class="text-nowrap align-middle"><span><?=$row['name']; ?></span></td>
                       <td class="text-center align-middle " style="  display: block;
width: 200px;
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;"><small><?=$row['description']; ?></small></td>
                       <td class="text-center align-middle"><?=$r['t']; ?></td>
                       <td class="text-center align-middle"><?=categoryName($row['category'])?></td>
                           <!-- <i class="fa fa-fw text-secondary cursor-pointer fa-toggle-on"></i> -->
                       
                       </tr>
                       <?php } ?>
                                 </tbody>
                             </table>
                         </div>
                     </div>
                     <div class="col-lg-3">
                         <h2 class="title-1 m-b-25">Top Clients</h2>
                         <div class="au-card au-card--bg-blue au-card-top-countries m-b-40">
                             <div class="au-card-inner">
                                 <div class="table-responsive">
                                     <table class="table table-top-countries">
                                         <tbody>
                                             <?php
                                                 foreach($topClients as $r){

                                             ?>
                                             <tr>
                                                 <td><?=customerDetails($r["cid"])['name']?></td>
                                                 <td class="text-right"><?=$r['t']?> Orders</td>
                                             </tr>
                                             <?php }
                                             ?>
                                         </tbody>
                                     </table>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="row">
                     <div class="col-lg-6">
                         <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
                             <div class="au-card-title" style="background-image:url('images/bg-title-01.jpg');">
                                 <div class="bg-overlay bg-overlay--blue"></div>
                                 <h3>
                                     <i class="zmdi zmdi-account-calendar"></i>Active orders</h3>
                                 <button class="au-btn-plus">
                                     <i class="zmdi zmdi-plus"></i>
                                 </button>
                             </div>
                             <div class="au-task js-list-load">
                                 <div class="au-task__title">
                                     <p>Active orders</p>
                                 </div>
                                 <div class="au-task-list js-scrollbar3">
                                     <?php 
                                         foreach ($activeOrders as $order):
                                     ?>
                                     <div class="au-task__item au-task__item--danger">
                                         <div class="au-task__item-inner">
                                             <h5 class="task">
                                                <?php 
                                                         echo getClient($order['clientId'])['name'];
                                                     foreach (getOrderDetails($order['ID']) as $orderDetails) {
                                                         foreach (getProductId($orderDetails['productId']) as $product ){
                                                 ?>

                                                 <?php
                                                 }?>
                                                 </h5>
                                                 <?php
                                                     }
                                                     ?>
                                                     <span class="time"><?=$order['approvalDate'];?></span>
                                                     </div>
                                     </div>
                                     <?php
                                         endforeach;
                                     ?>
                                     
                                 </div>
                                 <div class="au-task__footer">
                                     <a href="../order" class="au-btn ">go to orders</a>
                                 </div>
                             </div>
                         </div>
                     </div>
                     
                 </div>
                 <div class="row">
                     <div class="col-md-12">
                         <div class="copyright">
                             <p>Copyright © 2022 Dsi21. All rights reserved.</p>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- END MAIN CONTENT-->
     <!-- END PAGE CONTAINER-->
 </div>
 
</div>
<!-- <script type="text/javascript"> var monthwidget2 = "<php //echo "khra";?>" ; alert(monthwidget2);</script>  -->

