<div class="modal fade" role="dialog" tabindex="-1" id="user-delete-modal<?php echo $row['ID'];?>">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Delete Product</h5>
                  <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="py-1">
                    <form class="form" method="post" action="Pdelete.php" novalidate="">
                      <div class="row">
                        <div class="col">
                          <div class="row">
                            <div class="col">
                              <div class="form-group">
                                <label>Delete</label>
                                <input type="hidden" name="ID" value="<?php echo $row['ID']?>"/>
                                <h2>Are you sure you want to delete this item?</h2>
                              </div>
                            </div>

                          </div>

                          <div class="row">
                              <div class="col">
                                <div class="form-group float-right">
                                  <button type="reset" data-dismiss="modal" class="btn btn-danger float" >Cancel</button>
                                  <button type="submit" class="btn btn-primary float" >Confirm</button>
                                </div>
                              </div>
                            </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>